IF COMMAND$ = "" THEN SHELL "C:\VIRUS\F-PROT\F-PROT . /ALL /ANALYSE /BOOT /FILE /NOMEM /PACKED": END
IF UCASE$(COMMAND$) = "/I" THEN SHELL "C:\VIRUS\F-PROT\F-PROT": END
IF UCASE$(COMMAND$) = "-I" THEN SHELL "C:\VIRUS\F-PROT\F-PROT": END
SHELL "C:\VIRUS\F-PROT\F-PROT /ALL /ANALYSE /BOOT /FILE /NOMEM /PACKED " + COMMAND$: END

