<?
	$inventory = array(	array(	name => "Ted",
				price => 8.5,
				desc => "The original!",
				smallimage => "tedsmall.jpg",
				bigimage => "tedbig.jpg"),
			array(	name => "Hairy Potter",
				price => 14.75,
				desc => "Wizard bear.",
				smallimage => "hairypottersmall.jpg",
				bigimage => "hairypotterbig.jpg"),
			array(	name => "Frank",
				price => 9,
				desc => "Some standard model.",
				smallimage => "franksmall.jpg",
				bigimage => "frankbig.jpg"),
			array(	name => "Fred",
				price => 9.75,
				desc => "Yet another dull model, called Fred",
				smallimage => "fredsmall.jpg",
				bigimage => "fredbig.jpg"),
			array(	name => "Frits",
				price => 11.25,
				desc => "Frits the teddybear.",
				smallimage => "fritssmall.jpg",
				bigimage => "fritsbig.jpg"),
			array(	name => "Koos Werkeloos",
				price => 12,
				desc => "This is one lazy bear!",
				smallimage => "koossmall.jpg",
				bigimage => "koosbig.jpg"),
			array(	name => "Willem",
				price => 12.5,
				desc => "Willem saves the day.",
				smallimage => "willemsmall.jpg",
				bigimage => "willembig.jpg"));

?>
