# BNV_OUTLET table 

CREATE TABLE BNV_OUTLET
(
BNV_OUTLET VARCHAR2(15) NOT NULL,
BNV_ROOM VARCHAR(10) NOT NULL,
BNV_FLOOR NUMBER NOT NULL,
BNV_TEL_IP VARCHAR2(20),
BNV_SER_ADP NUMBER,
BNV_LSA_HWA NUMBER,
BNV_VLAN VARCHAR2(30),
BNV_HUB VARCHAR2(15),
BNV_PORT VARCHAR2(10),
BNV_SEGMENT VARCHAR2(15),
BNV_SEG_NAME VARCHAR2(30),
BNV_PERSON VARCHAR2(50),
BNV_EMAIL VARCHAR2(60),
BNV_LASTEDIT DATE NOT NULL,
BNV_EDITBY VARCHAR2(30),
BNV_COMMENTS VARCHAR2(255));
