# bnv_sessionlog table 

CREATE TABLE BNV_SESSIONLOG
(
SESSIONID VARCHAR2(15) NOT NULL,
USERID VARCHAR2(15) NOT NULL, 
REALNAME VARCHAR2(30) NULL,
STARTDATE DATE NOT NULL,
LANGUAGEID VARCHAR2(30) NOT NULL,
TYPELOGOUT VARCHAR2(30) NOT NULL,
EQS VARCHAR2(30) NOT NULL,
STAMPS NUMBER(9, 0) DEFAULT 0 NOT NULL
) 

GRANT all ON BNV_SESSIONLOG to SYSTEM;

COMMIT;
