# BNV_session table 

CREATE TABLE BNV_SESSION
(
SESSIONID VARCHAR2(15) NOT NULL,
USERID VARCHAR2(15) NOT NULL, 
REALNAME VARCHAR2(30),
STARTDATE DATE DEFAULT (SYSDATE) NOT NULL,
LANGUAGEID VARCHAR2(30),
TYPELOGOUT VARCHAR2(30),
EQS VARCHAR2(30),
STAMPS NUMBER(9, 0) DEFAULT 0 NOT NULL
);
