/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ADSERVER_H_RPCGEN
#define _ADSERVER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct price {
	float amount;
	int units;
};
typedef struct price price;

typedef struct {
	u_int pricelist_t_len;
	price *pricelist_t_val;
} pricelist_t;
#define FILENAME_LEN_MAX 256

typedef char *filename_t;

struct ad {
	filename_t filename;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct ad ad;

struct purchase {
	struct {
		u_int ads_len;
		struct ad *ads_val;
	} ads;
	int source_account;
	int certificate;
};
typedef struct purchase purchase;
#define ADSERVER_PRICES_FILE_BUFFER_SIZE 256

#define ADSERVER 400001
#define ADSERVER_VERS_1 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADSERVER_GET_PRICELIST 1
extern  pricelist_t * adserver_get_pricelist_1(void *, CLIENT *);
extern  pricelist_t * adserver_get_pricelist_1_svc(void *, struct svc_req *);
#define ADSERVER_PURCHASE_ADS 2
extern  int * adserver_purchase_ads_1(struct purchase *, CLIENT *);
extern  int * adserver_purchase_ads_1_svc(struct purchase *, struct svc_req *);
#define ADSERVER_GET_AD 3
extern  struct ad * adserver_get_ad_1(void *, CLIENT *);
extern  struct ad * adserver_get_ad_1_svc(void *, struct svc_req *);
#define ADSERVER_GET_NAMED_AD 4
extern  struct ad * adserver_get_named_ad_1(filename_t *, CLIENT *);
extern  struct ad * adserver_get_named_ad_1_svc(filename_t *, struct svc_req *);
extern int adserver_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADSERVER_GET_PRICELIST 1
extern  pricelist_t * adserver_get_pricelist_1();
extern  pricelist_t * adserver_get_pricelist_1_svc();
#define ADSERVER_PURCHASE_ADS 2
extern  int * adserver_purchase_ads_1();
extern  int * adserver_purchase_ads_1_svc();
#define ADSERVER_GET_AD 3
extern  struct ad * adserver_get_ad_1();
extern  struct ad * adserver_get_ad_1_svc();
#define ADSERVER_GET_NAMED_AD 4
extern  struct ad * adserver_get_named_ad_1();
extern  struct ad * adserver_get_named_ad_1_svc();
extern int adserver_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_price (XDR *, price*);
extern  bool_t xdr_pricelist_t (XDR *, pricelist_t*);
extern  bool_t xdr_filename_t (XDR *, filename_t*);
extern  bool_t xdr_ad (XDR *, ad*);
extern  bool_t xdr_purchase (XDR *, purchase*);

#else /* K&R C */
extern bool_t xdr_price ();
extern bool_t xdr_pricelist_t ();
extern bool_t xdr_filename_t ();
extern bool_t xdr_ad ();
extern bool_t xdr_purchase ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ADSERVER_H_RPCGEN */
