/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "adserver.h"
#include "adserver_util.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
adserver_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		struct purchase adserver_purchase_ads_1_arg;
		filename_t adserver_get_named_ad_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ADSERVER_GET_PRICELIST:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_pricelist_t;
		local = (char *(*)(char *, struct svc_req *)) adserver_get_pricelist_1_svc;
		break;

	case ADSERVER_PURCHASE_ADS:
		_xdr_argument = (xdrproc_t) xdr_purchase;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) adserver_purchase_ads_1_svc;
		break;

	case ADSERVER_GET_AD:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_ad;
		local = (char *(*)(char *, struct svc_req *)) adserver_get_ad_1_svc;
		break;

	case ADSERVER_GET_NAMED_AD:
		_xdr_argument = (xdrproc_t) xdr_filename_t;
		_xdr_result = (xdrproc_t) xdr_ad;
		local = (char *(*)(char *, struct svc_req *)) adserver_get_named_ad_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
  register SVCXPRT *transp;

  int retval = 0;

  if (argc == 3)
  {
    prices_file_name = argv[1];
    adserver_account = atoi(argv[2]);


    pmap_unset (ADSERVER, ADSERVER_VERS_1);

    transp = svcudp_create(RPC_ANYSOCK);
    if (transp == NULL) {
      fprintf (stderr, "cannot create udp service.");
      exit(1);
    }
    if (!svc_register(transp, ADSERVER, ADSERVER_VERS_1, adserver_1, IPPROTO_UDP)) {
      fprintf (stderr, "unable to register (ADSERVER, ADSERVER_VERS_1, udp).");
      exit(1);
    }
  
    transp = svctcp_create(RPC_ANYSOCK, 0, 0);
    if (transp == NULL) {
      fprintf (stderr, "cannot create tcp service.");
      exit(1);
    }
    if (!svc_register(transp, ADSERVER, ADSERVER_VERS_1, adserver_1, IPPROTO_TCP)) {
      fprintf (stderr, "unable to register (ADSERVER, ADSERVER_VERS_1, tcp).");
      exit(1);
    }
  
    svc_run ();
    fprintf (stderr, "svc_run returned");
    exit (1);
    /* NOTREACHED */
  }
  else // not enough arguments
  {
    fprintf(stdout, "Usage: %s <prices file> <adserver bank account>\n", argv[0]);
  }

  return retval;
}

