/*
 * File:           ConfigurationParslet.java
 * Date:           2 december 2003  20:15
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           2 december 2003  20:04
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           2 december 2003  19:44
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           2 december 2003  15:07
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           2 december 2003  14:49
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           26 November 2003  13:36
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           05 November 2003  22:44
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           29 October 2003  10:54
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           27 October 2003  18:37
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           27 October 2003  18:17
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           23 oktober 2003  11:49
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           14 October 2003  19:54
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  20:19
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  20:13
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  19:59
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  19:38
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  19:31
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  19:23
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
package configuration;

/*
 * File:           ConfigurationParslet.java
 * Date:           03 October 2003  10:54
 *
 * @author  Laurence Crutcher
 * @version generated by NetBeans XML module
 */
import org.xml.sax.*;

public interface ConfigurationParslet {
    
    public int routerIdConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String managementAgentConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String managementDomainConvertor(final java.lang.String data) throws SAXException;
    
    public int managementPortConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String hostConvertor(final java.lang.String data) throws SAXException;
    
    public boolean networkConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String httpPasswordConvertor(final java.lang.String data) throws SAXException;
    
    public int httpPortConvertor(final java.lang.String data) throws SAXException;
    
    public int metricConvertor(final java.lang.String data) throws SAXException;
    
    public boolean routerConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String addressElementConvertor(final java.lang.String data) throws SAXException;
    
    public int listenerPortConvertor(final java.lang.String data) throws SAXException;
    
    public boolean addressConvertor(final java.lang.String data) throws SAXException;
    
    public boolean managementKeyConvertor(final java.lang.String data) throws SAXException;
    
    public boolean destinationConvertor(final java.lang.String data) throws SAXException;
    
    public boolean connectionConvertor(final java.lang.String data) throws SAXException;
    
    public int distanceConvertor(final java.lang.String data) throws SAXException;
    
    public boolean interfaceConvertor(final java.lang.String data) throws SAXException;
    
    public boolean administrationConvertor(final java.lang.String data) throws SAXException;
    
    public boolean sourceConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String httpUserConvertor(final java.lang.String data) throws SAXException;
    
}

