/*
 * File:           ErikconfigurationParslet.java
 * Date:           4 december 2003  12:16
 *
 * @author  laurence.crutcher
 * @version generated by NetBeans XML module
 */
package configuration;

import org.xml.sax.*;

public interface ErikconfigurationParslet {
    
    public java.lang.String managementAgentConvertor(final java.lang.String data) throws SAXException;
    
    public int routerIdConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String managementDomainConvertor(final java.lang.String data) throws SAXException;
    
    public int managementPortConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String hostConvertor(final java.lang.String data) throws SAXException;
    
    public boolean networkConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String httpPasswordConvertor(final java.lang.String data) throws SAXException;
    
    public int httpPortConvertor(final java.lang.String data) throws SAXException;
    
    public int metricConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String messagingAgentConvertor(final java.lang.String data) throws SAXException;
    
    public boolean routerConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String addressElementConvertor(final java.lang.String data) throws SAXException;
    
    public int listenerPortConvertor(final java.lang.String data) throws SAXException;
    
    public boolean addressConvertor(final java.lang.String data) throws SAXException;
    
    public boolean managementKeyConvertor(final java.lang.String data) throws SAXException;
    
    public boolean destinationConvertor(final java.lang.String data) throws SAXException;
    
    public int distanceConvertor(final java.lang.String data) throws SAXException;
    
    public boolean connectionConvertor(final java.lang.String data) throws SAXException;
    
    public boolean interfaceConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String messagingDomainConvertor(final java.lang.String data) throws SAXException;
    
    public boolean administrationConvertor(final java.lang.String data) throws SAXException;
    
    public boolean sourceConvertor(final java.lang.String data) throws SAXException;
    
    public java.lang.String httpUserConvertor(final java.lang.String data) throws SAXException;
    
}

