<?


Function PopUp1()
{
?>

<DIV ID="searchKick" STYLE="POSITION: absolute; Z-INDEX: 20; VISIBILITY: hidden; TOP: 0px; LEFT: 0px;">
<TABLE BORDER=1 CELLPADDING=0 CELLSPACING=0>

<TR><TD width=300>
sdfasdf sdaf sdfg dfg fsdg dfsg dfsg dfsg
dfsg dsfg dfsg
<img scr="http://devedge.netscape.com/docs/manuals/images/bnr_sub_document.jpg">
</TD></TR>

</TABLE>
</DIV>

<?
}


/* einde van de style sheet */
?>
