/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "adserver.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

pricelist_t *
adserver_get_pricelist_1(void *argp, CLIENT *clnt)
{
	static pricelist_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADSERVER_GET_PRICELIST,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_pricelist_t, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
adserver_purchase_ads_1(struct purchase *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADSERVER_PURCHASE_ADS,
		(xdrproc_t) xdr_purchase, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct ad *
adserver_get_ad_1(void *argp, CLIENT *clnt)
{
	static struct ad clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADSERVER_GET_AD,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_ad, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
